fix: Delete useless Third party libraries dependencies declaration - Meeds-io/MIPs#42
Meeds-io/maven-depmgt-pom pull request #128
Opened 2023-07-20 14:00 UTC by boubaker

This change will delete useless Third party libraries versions declarations.

2023-07-25 09:04 UTC, rdenarie requested changes

2023-07-25 09:04 UTC, rdenarie commented on pom.xml
>      <org.apache.poi.version>5.2.2</org.apache.poi.version>
to delete ?

2023-07-25 09:04 UTC, rdenarie commented on pom.xml
>        </dependency>
to delete ?

2023-07-25 09:04 UTC, rdenarie commented on pom.xml
>        </dependency>
to delete ?

2023-07-26 09:25 UTC, rdenarie approved these changes

2023-07-26 09:47 UTC, boubaker commented on pom.xml
>      <org.apache.poi.version>5.2.2</org.apache.poi.version>
In fact, it's used by gamification when exporting XLSX. May be should be moved to gamification addon only.

2023-07-26 09:47 UTC, boubaker commented on pom.xml
>        </dependency>
In fact, it's used in Meeds packaging.

2023-07-26 09:49 UTC, boubaker commented on pom.xml
>        </dependency>
Seems used as third party library and packaged in Meeds.

2023-07-26 09:49 UTC, merged